#pragma once

enum BUTTONID{ BTN_SPACETOPLAY, BTN_NEWGAME, BTN_LOAD, BTN_CONFIG, BTN_REDARROW, 
	BTN_MAIN_MAX,
	BTN_GAME_START,
	BTN_RESUME, BTN_SAVE, BTN_LOAD2, BTN_RESTART, BTN_LOADLAST, BTN_MAINMENU, BTN_VILLAGE, BTN_EXITGAME, BTN_REDARROW2, 
	BTN_BUTTONTYPEMAX };
enum UIID{
	STATBAR, BLUEBAR, REDBAR, MAP_L_BORDER, MAP_TAG, 
	MN_NORMAL, MN_GAMEOVER,
	UI_ID_MAX };
