#pragma once

enum IN_FILE_DB_ID{
	FILE_MAIN_MENU_BG,
	FILE_BUTTON_SPACE_TO_PLAY,
	FILE_BUTTON_NEWGAME,
	FILE_BUTTON_LOAD,
	FILE_BUTTON_CONFIG,
	FILE_BUTTON_REDARROW,
	FILE_GAME_BG,
	FILE_GAME_PLAYER,
	FILE_GAME_TILEMAP,
	FILE_GAME_MOB_PORING,
	FILE_UI_STAT_BAR,
	FILE_UI_BLUEBAR,
	FILE_UI_REDBAR,
	FILE_UI_MAP_L_BORDER,
	FILE_UI_MAP_TAG,
	FILE_UI_BELT,
	FILE_UI_INVENTORY,
	FILE_UI_STAT,
	FILE_UI_HUD_MENU,
	FILE_MN_NORMAL,
	FILE_BTN_RESUME,
	FILE_BTN_SAVE,
	FILE_BTN_LOAD2,
	FILE_BTN_RESTART,
	FILE_BTN_MAINMENU,
	FILE_BTN_EXITGAME,
	FILE_BTN_REDARROW2,
	FILE_MN_GAMEOVER,
	FILE_BTN_LOADLAST,
	FILE_BTN_VILLAGE,
	FILE_ITEM_POTION_HEALTH_SMALL,
	FILE_ITEM_POTION_HEALTH_BIG,
	FILE_ITEM_POTION_HEALTH_1,
	FILE_ITEM_POTION_HEALTH_2,
	FILE_ITEM_POTION_HEALTH_3,
	FILE_ITEM_POTION_HEALTH_4,
	FILE_ITEM_POTION_MANA_SMALL,
	FILE_ITEM_POTION_MANA_BIG,
	FILE_ITEM_POTION_MANA_1,
	FILE_ITEM_POTION_MANA_2,
	FILE_ITEM_POTION_MANA_3,
	FILE_ITEM_POTION_MANA_4,
	FILE_SKILL1,
	FILE_SKILL2,
	FILE_MAP_ID_BUILDING,
	FILE_IN_FILE_DB_ID_MAX
};

enum SPRITEID{
	SPR_PLAYER,
	SPR_TILEMAP,
	SPR_MOB_PORING,
	SPR_ID_MAX
};

enum BUTTONID{ BTN_SPACETOPLAY, BTN_NEWGAME, BTN_LOAD, BTN_CONFIG, BTN_REDARROW, 
	BTN_MAIN_MAX,
	BTN_GAME_START,
	BTN_RESUME, BTN_SAVE, BTN_LOAD2, BTN_RESTART, BTN_LOADLAST, BTN_MAINMENU, BTN_VILLAGE, BTN_EXITGAME, BTN_REDARROW2, 
	BTN_BUTTONTYPEMAX };

enum UIID{
	STATBAR, BLUEBAR, REDBAR, MAP_L_BORDER, MAP_TAG, 
	MN_NORMAL, MN_GAMEOVER, UI_BELT, UI_INVENTORY, UI_STAT, UI_HUD_MENU,
	UI_ID_MAX };

enum MAPOBJECT{
	MAP_ID_BUILDING,
	MAP_OBJECT_MAX
};

enum ITEM_TYPE
{
	ITEM_EQUIPMENT,		// effect to static stat
	ITEM_CONSUME,		// effect to current stat
	ITEM_TYPE_MAX
};

enum ITEM_CONSUME_ID
{
	ITEM_POTION_HEALTH_SMALL,	// potion effect
	ITEM_POTION_HEALTH_BIG,		// potion effect
	ITEM_POTION_HEALTH_1,		// potion effect
	ITEM_POTION_HEALTH_2,		// potion effect
	ITEM_POTION_HEALTH_3,		// potion effect
	ITEM_POTION_HEALTH_4,		// potion effect
	ITEM_POTION_MANA_SMALL,
	ITEM_POTION_MANA_BIG,
	ITEM_POTION_MANA_1,
	ITEM_POTION_MANA_2,
	ITEM_POTION_MANA_3,
	ITEM_POTION_MANA_4,
	ITEM_CONSUME_MAX
};

enum ITEM_EQUIP_ID
{
	ITEM_SWORD_ARMINGSWORD,
	ITEM_SWORD_BASTARDSWORD,
	ITEM_EQUIP_MAX
};

enum GEFFECT_ID{
	SKILL1,
	SKILL2,
	HEALTHPOTION,	
	GEFFECT_ID_MAX
};

typedef struct Effect
{
	float HP;
	float MP;
	float Attack;
	float AttackSpeed;
	float Defense;
	float MoveSpeed;
}EFFECT, *LPEFFECT;

static EFFECT Item_Equip_DB[ITEM_EQUIP_MAX] = {
		{ 0, 0, 100.0f, 0, 0, 0 },
		{ 0, 0, 200.0f, 0, 0, 0 }
};

static EFFECT Item_Consume_DB[ITEM_CONSUME_MAX] =
{
	{ 100, 0, 0, 0, 0, 0 },	//ITEM_POTION_HEALTH_SMALL
	{ 200, 0, 0, 0, 0, 0 },	//ITEM_POTION_HEALTH_BIG
	{ 300, 0, 0, 0, 0, 0 }, //ITEM_POTION_HEALTH_1
	{ 400, 0, 0, 0, 0, 0 }, //ITEM_POTION_HEALTH_2
	{ 500, 0, 0, 0, 0, 0 }, //ITEM_POTION_HEALTH_3
	{ 600, 0, 0, 0, 0, 0 }, //ITEM_POTION_HEALTH_4
	{ 0, 10, 0, 0, 0, 0 }, //ITEM_POTION_MANA_SMALL,
	{ 0, 20, 0, 0, 0, 0 }, //ITEM_POTION_MANA_BIG,
	{ 0, 30, 0, 0, 0, 0 }, //ITEM_POTION_MANA_1,
	{ 0, 40, 0, 0, 0, 0 }, //ITEM_POTION_MANA_2,
	{ 0, 50, 0, 0, 0, 0 }, //ITEM_POTION_MANA_3,
	{ 0, 100, 0, 0, 0, 0 }, //ITEM_POTION_MANA_4,
};
